ALTER TABLE "trades"
    ADD COLUMN "order_matching_fee_sat" BIGINT NOT NULL DEFAULT 0,
    DROP COLUMN IF EXISTS "fee_payment_hash";

UPDATE TRADES SET ORDER_MATCHING_FEE_SAT = (QUANTITY * (1 / AVERAGE_PRICE) * 0.003) * 100000000;
