/// Flutter icons CustomIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData codeBranchSolid =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codeCompareSolid =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkSolid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData node = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData version = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peer = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData looksOne = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
