default_platform(:android)

APP_SCHEME = ENV["FASTLANE_ANDROID_APP_SCHEME"]

platform :android do

  desc "Submit a new build to google play store"
  lane :alpha do
    changelog = File.read("../../../CHANGELOG.md")
    upload_to_play_store(
        track: 'alpha',
        aab: "../build/app/outputs/bundle/#{APP_SCHEME}Release/app-#{APP_SCHEME}-release.aab",
    )
  end
end
