# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new build to google play store"
  lane :alpha do
    changelog = File.read("../../../CHANGELOG.md")
    upload_to_play_store(
    track: 'alpha',
    version_name:'1.1.0',
     aab: "../build/app/outputs/bundle/demoRelease/app-demo-release.aab",
    )
  end

end
