// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  final String network;

  DefaultFirebaseOptions(this.network);

  FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        switch (network) {
          case "regtest":
            return androidDemo;
          case "mainnet":
          default:
            return androidProd;
        }
      case TargetPlatform.iOS:
        switch (network) {
          case "regtest":
            return iosTest;
          case "mainnet":
          default:
            return iosProd;
        }
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyCDI7arcBp4uriwfLySgqrchkNVDVW94uk',
    appId: '1:237191932527:android:651be56a933e8bda36bb9a',
    messagingSenderId: '237191932527',
    projectId: 'project-3195624368411891722',
    storageBucket: 'project-3195624368411891722.appspot.com',
  );

  static const FirebaseOptions androidDemo = FirebaseOptions(
    apiKey: 'AIzaSyC6pSZrKdL69ch2ltopWjSqmu31icNZL-U',
    appId: '1:958970316277:android:c8a1d7a58212e3111e0cbc',
    messagingSenderId: '958970316277',
    projectId: 'testnet-467c6',
    storageBucket: 'testnet-467c6.appspot.com',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyD1FiZUHkX-rdHUtAXU12ku2e7zmBHqLSQ',
    appId: '1:237191932527:ios:ed5586aaa838be1e36bb9a',
    messagingSenderId: '237191932527',
    projectId: 'project-3195624368411891722',
    storageBucket: 'project-3195624368411891722.appspot.com',
    iosClientId: '237191932527-70uoogr06k3rrrmslr5u1r6i4st9ch39.apps.googleusercontent.com',
    iosBundleId: 'finance.get10101.app',
  );

  static const FirebaseOptions iosTest = FirebaseOptions(
    apiKey: 'AIzaSyC1DcfWnlt0BQMpX7_z3f0QPTgL1Po7zB8',
    appId: '1:958970316277:ios:b85e19a35086fb681e0cbc',
    messagingSenderId: '958970316277',
    projectId: 'testnet-467c6',
    storageBucket: 'testnet-467c6.appspot.com',
    iosClientId: 'unset?!?',
    iosBundleId: 'finance.get10101.app.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1FiZUHkX-rdHUtAXU12ku2e7zmBHqLSQ',
    appId: '1:237191932527:ios:ed5586aaa838be1e36bb9a',
    messagingSenderId: '237191932527',
    projectId: 'project-3195624368411891722',
    storageBucket: 'project-3195624368411891722.appspot.com',
    iosClientId: '237191932527-70uoogr06k3rrrmslr5u1r6i4st9ch39.apps.googleusercontent.com',
    iosBundleId: 'finance.get10101.app',
  );
}
